version: 2.1
orbs:
  codecov: codecov/codecov@1.1.1
jobs:
  build:
    working_directory: ~/sampleCircleCI
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run:
          name: Functional verification
          command: nosetests test/test.py
      - run:
          name: Check coding rules (PEP8)
          command: flake8 src
          when: always
      - run:
          name: Coverage verification
          command: |
            coverage run test/test.py
            codecov
          when: always

