version: 2.1
orbs:
  codecov: codecov/codecov@1.1.1
jobs:
  build:
    working_directoyr: ~/sampleCircleCI
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: nosetests test/test.py
      - run: flake8 ./ src
      - codecov/upload:
          file: ./coverage.out
