version: 2
jobs:
  build:
    working_directoyr: ~/sampleCircleCI
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          pip install --upgrade pip
      - run:
          command: pip install -r requirements.txt
      - run:
          command: nosetests test/test.py