version: 2
jobs:
  build:
    working_directoyr: ~/sampleCircleCI
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: apt-get update
      - run:
          command: pip install -r requirements.txt
      - run:
          command: nosetests test/test.py