version: 2
jobs:
  build:
    working_directoyr: ~/sampleCircleCI
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: apt-get update && apt-get install -y
      - run:
          command: sudo pip install -r requirements.txt
      - run:
          command: python test/test.py